In [2]:
"""
Numpy
Linear Algebra lib python 
math and log operation on array(both in Multidimen)
"""

import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
#2D Array 
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
#Numpy array initialization 
#1 all elemets of a x*y with 0

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
#Arranging the numbers betwen X & Y with an interval of Z
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [8]:
# even numbers between 10 and 20
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [9]:
# arranging z numbers between x and y

In [10]:
np.linspace(5, 10, 10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [12]:
np.linspace(5, 10, 5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [13]:
np.linspace(0, 10, 6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [14]:
#filling same no in  a arraay of din X*Y

np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [18]:
#filling random numbers in a array 
np.random.random((2,3))

array([[0.95793927, 0.15090851, 0.69232556],
       [0.17549726, 0.50537972, 0.0661379 ]])

### Inspecting a Numpy Array 

In [19]:
#np.shape()

a = np.array([[2,3,4],[4,4,6]])
print(a.shape)

(2, 3)


In [20]:
b = np.array([[1,2,3,4],[2,3,4,6],[6,7,8,9]])
print(b.shape)

(3, 4)


In [22]:
#Resizing the array 

a = np.array([[2,3,4],[4,4,6]])
a.shape = (3,2)
print(a)

[[2 3]
 [4 4]
 [4 6]]


In [23]:
a = np.array([[2,3,4,4],[2,4,4,6]])
a.shape = (8,1) # Trick: X*y = total number of elements in array 
print(a)

[[2]
 [3]
 [4]
 [4]
 [2]
 [4]
 [4]
 [6]]


In [25]:
#return the dimentsion of arrau 
a = np.arange(24)
print(a.ndim)
#reshaping
b = a.reshape(2,4,3)
print(b)
print(b.ndim)

1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
3


In [28]:
# Find the number of elemetns in a array 
a = np.arange(24)
print(a.size)

24


In [31]:
a = np.arange(24)
a.dtype

dtype('int32')

In [32]:
a = np.arange(24, dtype = float)
a.dtype

dtype('float64')

### Numpy array Maths 

In [34]:
#sum of all the elemts, this is the default value 
np.sum([[10, 20],[10,20]])

60

In [35]:
#sum of individual rows
np.sum([[10, 20],[10,20]], axis =1)

array([30, 30])

In [36]:
#Sum of individual coloums
np.sum([[10, 20],[10,20]], axis =0)

array([20, 40])

In [40]:
#similary sub divide or  mul
np.subtract(10,20)#,[10,20]])

-10

In [41]:
a = np.array([2,4,6])
b = np.array([1,2,3])
np.multiply(a,b)

array([ 2,  8, 18])

In [42]:
a = np.array([[2,4,6],[1,2,3]])
b = np.array([[1,2,3],[1,2,3]])
np.multiply(a,b)

array([[ 2,  8, 18],
       [ 1,  4,  9]])

In [45]:
#Similarly we have other function
a = np.array([2,4,6])
print("Exponenet:", np.exp(a))
print("Sq rt:", np.sqrt(a))
print("Sin:", np.sin(a))
print("Cos:", np.cos(a))
print("Log:", np.log(a))

Exponenet: [  7.3890561   54.59815003 403.42879349]
Sq rt: [1.41421356 2.         2.44948974]
Sin: [ 0.90929743 -0.7568025  -0.2794155 ]
Cos: [-0.41614684 -0.65364362  0.96017029]
Log: [0.69314718 1.38629436 1.79175947]


In [47]:
#Array Comparison 
#element wise comparison
a = [1,2,3]
b = [2,3,4]
c = [1,3,0]
print(np.equal(a,b))
print(np.equal(a,c))
print(np.equal(b,c))

[False False False]
[ True False False]
[False  True False]


In [48]:
a = [1,2,3]
b = [2,3,4]
c = [1,2,3]
print(np.array_equal(a,b))
print(np.array_equal(a,c))
print(np.array_equal(b,c))

False
True
False


In [50]:
#Aggregate Functions

a = [1,2,3]
b = [2,3,4]
c = [1,3,0]

print("Sum:",np.sum(a))
print("Min Val:",np.min(a))
print("Mean:",np.mean(a))
print("Median:",np.median(a))
print("Corelation Coeff:",np.corrcoef(a))
print("Standard dev:",np.std(a))

Sum: 6
Min Val: 1
Mean: 2.0
Median: 2.0
Corelation Coeff: 1.0
Standard dev: 0.816496580927726


In [52]:
#Numpy Broadcasting

a = np.array([[0,0,0],[1,2,3],[4,5,6],[5,6,7]])
b = np.array([0,1,2])
print("First array: \n", a, "\n")
print("Second array: \n", b, "\n")
print("1st + 2nd:\n", a+b)



First array: 
 [[0 0 0]
 [1 2 3]
 [4 5 6]
 [5 6 7]] 

Second array: 
 [0 1 2] 

1st + 2nd:
 [[0 1 2]
 [1 3 5]
 [4 6 8]
 [5 7 9]]


### Numpy Array manuplation 

In [58]:
#concatenation, stacking row-wise: Vertically, row-wise: Horizontal and coloun-wise


a = np.array([1,2,3])
b = np.array([4,5,6])
#Concatenate

print("concatenate\n", np.concatenate((a,b)))
#row-wise: Horizontal
print("Horizontal_stack\n", np.hstack((a,b)))
#stacking row-wise: Vertically
print("vertical_stack\n",np.vstack((a,b)))
#Stacking coloum-wise
print("Coloum wise\n", np.column_stack((a,b)))

concatenate
 [1 2 3 4 5 6]
Horizontal_stack
 [1 2 3 4 5 6]
vertical_stack
 [[1 2 3]
 [4 5 6]]
Coloum wise
 [[1 4]
 [2 5]
 [3 6]]


In [65]:
# Splitting Array 
x= np.arange(16).reshape(4,4)
print(x,"\n")
print("\n\nSpliting Horizontally:\n", np.hsplit(x,2))
print("\n\nCustom Split\n:", np.hsplit(x,np.array([2,3])))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 



Spliting Horizontally:
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


Custom Split
: [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


#### Indexing and slicing in Numpy 

In [67]:
a = ['m','o','n','t','y',' ','p','y','t','h','o','n']

In [68]:
a[0:5]

['m', 'o', 'n', 't', 'y']

In [70]:
a[6:12]

['p', 'y', 't', 'h', 'o', 'n']

In [73]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0],'\n')
print(a[1:,:])

[1 2 3] 

[[4 5 6]
 [7 8 9]]


In [74]:
print(a[1:,1:])

[[5 6]
 [8 9]]


#### Numpy Vs List

In [76]:
#Numpy : Less Memory, Faster and Convinent 

import sys
l = range(1000)
print("Size of the list:", sys.getsizeof(1)*len(l))

a = np.arange(1000)
print("Size of the array", a.size*a.itemsize)


Size of the list: 28000
Size of the array 4000


In [90]:
#Comparision in terms of Speed
import time

def using_List():
    t = time.time() #Initial Time
    X = range(100000)
    Y = range(100000)
    Z = [X[i]+Y[i] for i in range(len(X))]
    return time.time()- t

def using_Numpy():
    t = time.time()
    a =np.arange(100000)
    b = np.arange(100000)
    z= a+b
    return time.time()- t




In [92]:
list_time = using_List()
Numpy_time = using_Numpy()

print(list_time*100, Numpy_time*100)

5.1581621170043945 0.049686431884765625


In [ ]:
# SCIPY

"""
Used for scientific and technical computing

Contains modules for optimization, Lin Algebra, Integration, Interpolation, 
Special Fun, Fourier transform, Signal and image processing

Operates on numpy

SciPy Sub-packages
scipy.cluster: for vectors
scipy.stats
scipy.optimize
scipy.integrate
scipy.linalg
scipy.fftpack
scipy.signal

"""

In [93]:
import scipy.cluster

In [94]:
from scipy import linalg 
import numpy as np 
new=np.array([[0.1,1,2],[3,0.2,1],[1,0.5,4]])
linalg.det(new)

-8.370000000000001

In [95]:
import numpy 
array_1 = numpy.array([[1,2,3],[0,0,0]])
array_2 = numpy.array([[0,0,0],[7,8,9]]) 
print(numpy.concatenate((array_1, array_2), axis = 1))

[[1 2 3 0 0 0]
 [0 0 0 7 8 9]]


In [101]:
import numpy as np 
from scipy import stats 
new=np.array([[0.1,1,2],[3,0.2,1],[1,0.5,4]]) 
_,p,_,_ =stats.chi2_contingency(new) 

In [102]:
p

0.24642879111750018

In [100]:
from scipy.cluster.vq import kmeans,vq,whiten 
import matplotlib.pyplot as plt 
new=[0.1,1,3,0.2,1,0.5,12,0.2,10,0.5,10,2,5,0.8] 
plt.scatter(range(len(new)),new) 
centroid,_ = kmeans(new,2) 
idx, _ = vq(new,centroid) 
idx

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1])

In [103]:
import numpy 
my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9]) 
print(numpy.ceil(my_array))

[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
